# Generated by Django 4.2.13 on 2024-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowNumber', models.TextField()),
                ('REF_WP', models.TextField()),
                ('CAT1', models.TextField()),
                ('CAT2', models.TextField()),
                ('MEMO_TIME', models.TextField()),
                ('SERIAL_NO', models.TextField()),
                ('stitle', models.TextField()),
                ('xbody', models.TextField()),
                ('xurl', models.TextField()),
                ('idpt', models.TextField()),
                ('address', models.TextField()),
                ('fileurl', models.TextField()),
                ('info', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('MRT', models.TextField()),
            ],
            options={
                'db_table': 'storymap',
            },
        ),
    ]
